### ISSUE TITLE
Switches not working? No sliders?

### ISSUE THREAD

**Issue by BrettWa** [vinteo/hass-opensprinkler#12] opened 2018-10-27 08:19 UTC
Trying this out - I'm getting all the components generated (sensor, binary_sensor, switches, etc) - but see no time sliders? 

When I try run a switch, it immediately turns off, logging the following, which makes me think it's looking for an "on time" slider.
```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/service.py", line 224, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/switch/hass_opensprinkler.py", line 47, in turn_on
    self._station.turn_on(int(float(mins.state)))
AttributeError: 'NoneType' object has no attribute 'state'

```

I've tried on multiple versions of HA 0.80*

**Comment by vinteo** [comment] 2018-10-28 23:04
You are the second person to report this (https://github.com/vinteo/hass-opensprinkler/issues/11) so there must be an issue, but it works for me and I only have my instance to test on. Are you using hass.io? Can you share your station names?

As mentioned in the other issue, you should be able to get around it for now by creating the timer manually

**Comment by BrettWa** [comment] 2018-10-29 05:31
Ah - apologies, read the titles and didn't see anything.

I'm running HA in a docker container.

I'll try manually creating the sliders when I get home - I know something changed with the sliders in general with 0.80* - a couple of my other input sliders starting displaying differently.

Station names are fairly standard (see  picture)
![capture](https://user-images.githubusercontent.com/36360813/47630972-7747ed00-db4c-11e8-8468-aa5a9d015c6b.JPG)

**Comment by BrettWa** [comment] 2018-10-29 14:13
I can confirm manually creating the sliders works.

**Comment by vinteo** [comment] 2018-10-30 00:11
Great, I will try look at a fix when I have time

**Comment by ruimarinho** [comment] 2018-11-25 18:36
Same thing happening to me:

```
2018-11-25 18:34:42 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall switch.turn_on (c:1294d8bc10bf4b92a3753d435733da7b): entity_id=['switch.neighbour_back']>
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/core.py", line 1115, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/src/app/homeassistant/components/switch/__init__.py", line 109, in async_handle_switch_service
    await switch.async_turn_on()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/switch/hass_opensprinkler.py", line 47, in turn_on
    self._station.turn_on(int(float(mins.state)))
AttributeError: 'NoneType' object has no attribute 'state'
```

**Comment by ruimarinho** [comment] 2018-11-25 19:46
I don't see any timers @vinteo. How may I help debugging the issue?

**Comment by vinteo** [comment] 2019-02-25 06:03
Sorry for the late update but I did try and look at creating the input sliders in a different way but could not get it working after trying it for a few days. I don't think hass has an official way to programmatically create input sliders from a component (as I could not find any examples or docs on it) so the way I did it may be a bit of a hack.

Anyone with any ideas please let me know

**Comment by JurajNyiri** [comment] 2019-08-29 16:46
Suddenly started encountering this error. Was working fine before, didn't change home assistant environment nor updated ospi.

```
'NoneType' object has no attribute 'state'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 210, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 349, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 371, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hass_opensprinkler/switch.py", line 47, in turn_on
    self._station.turn_on(int(float(mins.state)))
AttributeError: 'NoneType' object has no attribute 'state'
```

When I have the time I will dig deeper.

**Comment by JurajNyiri** [comment] 2019-08-30 22:56
Fixed it with https://github.com/vinteo/hass-opensprinkler#my-sprinkler-switches-are-not-working

**Comment by vinteo** [comment] 2019-11-21 00:04
thanks @JurajNyiri for finding the root cause

So it seems that if you have any input_number entities in your config, the input_number entities will not be setup automatically and have to be setup manually. 

Please refer to the trouble shooting guide in the README on how to do this.

Will close this issue now

**Closed by vinteo** 2019-11-21 00:04 UTC
