### ISSUE TITLE
[%key:common::config_flow::error::unknown%]

### ISSUE THREAD

**Issue by Trynius** [vinteo/hass-opensprinkler#125] opened 2020-07-29 20:32 UTC
OpenSprinkler v3.2, firmware: 2.1.9 rev4
Home Assistant 0.112.1

I can setup the integration via HACS, but when I attempt to configure it, I receive this error. 

[%key:common::config_flow::error::unknown%]

These are the additional details spit out in the log file:

Traceback (most recent call last):
  File "/config/custom_components/opensprinkler/config_flow.py", line 53, in async_step_user
    await controller.refresh()
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 218, in refresh
    await self._refresh_state()
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 236, in _refresh_state
    content = await self.request("/ja")
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 147, in request
    content = await self._request_http(url)
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 193, in _request_http
    content = await resp.json(encoding="UTF-8")
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1031, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url='http://10.110.4.105/ja?pw="encryptedPW"

When I go to the URL directly, it works fine, but the behavior when trying to configure it is consistent. Any thoughts? :(

**Comment by vinteo** [comment] 2020-07-29 22:07
What do you see exactly when you go to the URL directly?

I see you installed the beta version, could you try the non beta version and see if it works for comparison?

**Comment by Trynius** [comment] 2020-07-29 22:18
*facepalm*... great catch. I installed 1.0.8 and it worked like a charm.

If you'd like my help troubleshooting the beta, let me know. For what it's worth, when I go to the opensprinkler URL directly, it displays an html page with json formatted data on it. The recommended fix after my research was to use:

await resp.json(content_type='text/html')

You fixed my problem before I had the chance to try modifying the pyopensprinkler file with that.

**Comment by vinteo** [comment] 2020-07-29 22:32
I will do more testing on the beta version around that, I might get you to test it for me :)

**Comment by vinteo** [comment] 2020-07-29 23:52
@Trynius I could not reproduce your OpenSprinkler response with content type `text/html`, are you using some proxy by any chance?

However I did make a change to use the content type of the response when decoding the JSON and released `v1.1.0-beta.4`, can you see if that works for you?

**Comment by Trynius** [comment] 2020-07-29 23:57
No proxy in-use. I'll give the beta a shot and see what happens. FWIW, I can't get the opensprinkler.run service to function yet either... lol, but I've barely started troubleshooting. Always something with HA, I swear.

**Comment by Trynius** [comment] 2020-07-30 00:04
That update resolved the integration issue for me, thank you! I'll keep working at the service call and see if I can get that working too. Getting this error "Unable to find referenced entities switch.s04_station_enabled", which is super fun since it's definitely there. More to come... but you can close this issue if you'd like! :)

**Comment by vinteo** [comment] 2020-07-30 00:09
That looks like an HA error.

I close this for now. Thanks for your help

**Closed by vinteo** 2020-07-30 00:09 UTC

**Comment by sdwilsh** [comment] 2020-07-30 01:41
Should the error message really be `[%key:common::config_flow::error::unknown%]`?  That looks like it didn't pull a string from somewhere.

**Comment by vinteo** [comment] 2020-07-30 06:42
Yea it works for a core integrations but it doesn't for custom integrations. But I read somewhere they were planning to make it work for custom integrations which is why I left it and it does for our purposes say enough to let us know what is the error for now.
