### ISSUE TITLE
Binary Sensor Program does not change state

### ISSUE THREAD

**Issue by Mark612** [vinteo/hass-opensprinkler#134] opened 2020-09-15 00:40 UTC
I've used my "home grown" program for over two years now, and stumbled across this. Great work!

I noticed that all my switches, sensors, and binary sensors seem to work fine. (I have 7 stations, and 2 programs). 

However, the binary_sensor.program_running seems to not change state.

May be me, still troubleshooting my setup. But, a little strange everything worked except this.

**Comment by Mark612** [comment] 2020-09-15 20:20
Sounds like you are on the right track. /mp&pid=x will run once the program index x. When I use this, the binary sensor shows the program running properly, bit is flipped.

For some reason I couldn't find it in the new API documentation, so not sure if it is still available for the newer firmware.

**Comment by matticas** [comment] 2020-12-03 21:24
Hi, i have just discovered this same condition.
Binary-sensor.program_name_running does not change state if when the program runs or stops.
Is there any tests you would like me to run to confirm on a seperate platform?
I have OSPi hardware and currently HA 0.118.x

**Comment by vinteo** [comment] 2021-05-29 23:18
I have confirmed that with a manual run of the a program (ie `/mp?pid=X`), OS treats this as a once off program thus does not provide the pid through its API for the current running program. You can see this on the OS Web UI when you manually run a program as well (it will say "run-once program") So instead of the pid of the program it provides `254` which is a special pid for run-once programs. I guess this kind of makes sense as a "program" will include the scheduled time so a manual run technically is not the program on its whole when run manually.

Since this integration (and the supporting library) does not do anything beyond providing what's on the OS API (and don't plan to), I don't think this will change. 

Are you guys relying on this for some sort of automation?

**Comment by Mark612** [comment] 2021-05-29 23:23
Hi Vincent,
Yes.

It is nice to be able to run a program manually vs. waiting for a schedule triggered event.

I use the state to determine if the program is still running after being executed. If you have a station running, it is nice to know if it is part of the overall program or just a single station being run.

**Comment by vinteo** [comment] 2021-05-29 23:50
Yes it would be nice but like I said the OS API does not provide this information in this scenario unless I am missing something (check API docs here: https://openthings.freshdesk.com/support/solutions/articles/5000716363)

One way is to perhaps store the pid on an `input_number` when you trigger the manual run and build your own sensor from that.

**Comment by Mark612** [comment] 2021-05-29 23:52
> 
> ...perhaps store the pid on an `input_number` when you trigger the manual run and build your own sensor from that using the template sensor....

Yes.

**Comment by vinteo** [comment] 2021-05-29 23:55
Just to confirm, this only happens on a manual run? For the scheduled runs, the binary sensors show correctly? If so I might close this issue.

**Comment by Mark612** [comment] 2021-05-30 00:05
> Just to confirm, this only happens on a manual run? For the scheduled runs, the binary sensors show correctly? If so I might close this issue.

> Just to confirm, this only happens on a manual run? For the scheduled runs, the binary sensors show correctly? If so I might close this issue.

Good question. Unfortunately, I reverted back to my python code for running my sprinklers as I needed this functionality. I don't store the state anywhere. So, there is an ability through the API and/or logic to get it.

I will not be able to reinstall your code, or review my own code for awhile. As such, you may want to close this issue if other users are not having the same problem.

Good luck.

**Closed** 2021-05-30 00:08 UTC
