### ISSUE TITLE
Last run date shown in UTC

### ISSUE THREAD

**Issue by AlBrough** [vinteo/hass-opensprinkler#129] opened 2020-08-08 11:42 UTC
"Last run date" seems to be stored as a UTC time despite my OpenSprinker and Home Assistant setup being the same time zone. 

Is there something I am missing or is this by design?

I am trying to do some simple date calculations to get an integer of the number of days to appear on a badge on my dashboard, there seems to be a "days since last run" available for an entity but I can't seem to get it to add to a badge

**Comment by vinteo** [comment] 2020-08-08 11:45
By design it is stored as UTC in the DB (I think) but I believe it should be shown in your HA time if you use the lovelace cards (it shows in my local time when I use the glance card for example). If you are using some custom calculations it might need some conversion.

**Comment by vinteo** [comment] 2020-08-09 00:15
this might be of help: https://www.home-assistant.io/docs/configuration/templating/#time

**Comment by vinteo** [comment] 2020-08-17 09:04
@AlBrough di you figure this out? Can we close this issue?

**Comment by AlBrough** [comment] 2020-08-18 00:20
I have created a template and worked it out. Thanks for the link, it was enough for me to work out what I needed.

**Closed** 2020-08-18 00:19 UTC
